easy_admin:
    entities:
        - App\Entity\User
        - App\Entity\Speaker
        - App\Entity\Subscriber
        - App\Entity\Speak
        - App\Entity\Subscription
        - App\Entity\Event
        - App\Entity\CallForPaper
