version: "3.4"
services:

  api: 
    image: gerardojunior/symfony.environment:stable
    restart: on-failure
    volumes:
      - type: bind
        source: ./
        target: /usr/share/src
    ports:
      - 1234:80
